# Generated by Django 2.1.14 on 2019-11-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personalId', models.CharField(blank=True, max_length=14)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('surname', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('percent', models.CharField(max_length=255)),
            ],
        ),
    ]
