# Generated by Django 2.1.14 on 2019-11-27 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realperson',
            old_name='phone',
            new_name='Phone',
        ),
        migrations.RenameField(
            model_name='realperson',
            old_name='personalId',
            new_name='personal_id',
        ),
    ]
