version: '3.7'

services:
 eureka-server:
   build:
    context: eurekaserver
    dockerfile: Dockerfile
   ports:
    - "8761:8761"

 companya:
   build:
    context: companya
    dockerfile: Dockerfile
   ports:
    - "8200:8200"

 companyb:
   build:
    context: companyb
    dockerfile: Dockerfile
   ports:
    - "8202:8202"

 compare-data:
   build:
     context: to-percent
     dockerfile: Dockerfile
   ports:
     - "8400:8400"
   links:
     - eureka-server
   depends_on:
     - eureka-server
   environment:
     EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka

 netflixzull:
   build:
     context: netflixzull
     dockerfile: Dockerfile
   ports:
     - "9090:9090"
   links:
     - eureka-server
   depends_on:
     - eureka-server
   environment:
     EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka

 app:
   user: $UID:$GID
   build:
     context: sop2019
     dockerfile: Dockerfile
   ports:
     - "8000:8000"
   command: sh -c "pip install -r requirements.txt && tail -f /dev/null"
   volumes:
     - ./sop2019/app:/app:Z

 data-format:
   user: $UID:$GID
   build:
     context: dataformat
     dockerfile: Dockerfile
   ports:
     - "8300:8300"
   command: sh -c "tail -f /dev/null"
   volumes:
     - ./dataformat/app:/app:Z

