version: '3.7'

services:
 eureka-server:
   build:
    context: eurekaserver
    dockerfile: Dockerfile
   ports:
    - "8761:8761"

 companya:
   build:
    context: companya
    dockerfile: Dockerfile
   ports:
    - "8200:8200"

 companyb:
   build:
    context: companyb
    dockerfile: Dockerfile
   ports:
    - "8202:8202"

 netflixzull:
   command: sh -c "sleep 60;"
   build:
     context: netflixzull
     dockerfile: Dockerfile
   ports:
     - "9090:9090"
   environment:
     - HOSTNAMEAPP=app
   restart: on-failure
   depends_on:
     - app
   links:
     - app

 app:
   user: $UID:$GID
   build:
     context: sop2019
     dockerfile: Dockerfile
   ports:
     - "8000:8000"
   command: sh -c "pip install -r requirements.txt && tail -f /dev/null"
   volumes:
     - ./sop2019/app:/app:Z
   healthcheck:
     test: ["CMD", "curl", "-f", "http://localhost:8000"]
     interval: 30s
     timeout: 10s
     retries: 5
